### Project Euler
### Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Initialise variables & Constants
prevNum = 1         # Previous number in the sequence
currentNum = 2      # Number currently being considered
total = 0           # Running total of even fib nums
LIMIT = 4000000     # Limit to check until


# Program Loop
while currentNum <= LIMIT:
    # Check if current even and if so add to total
    if currentNum % 2 == 0:
        total += currentNum

    # Calc next number and move current to previous
    prevNum, currentNum = currentNum, prevNum + currentNum

print(total) # output result
    
